config/routes.rb
Rails.application.routes.draw do

  namespace :campagne do
    root to: 'campagne_lists#index'
    resources :campagne_lists do
      member do
        get 'import'
        post 'import'
      end
    end
    resources :campagne_campaigns do
      member do
        get 'preview'
        get 'deliveries'
        post 'schedule'
      end
    end
    get 'see/:token' => 'campagne_deliveries#see'
    get 'click/:token' => 'campagne_deliveries#click'
    get 'unsubscribe/:token' => 'campagne_deliveries#unsubscribe'
    get 'bounce/:token' => 'campagne_deliveries#bounce'
  end

end

app/models/campagne/campagne_campaign.rb
module Campagne
  class CampagneCampaign < ActiveRecord::Base
    has_and_belongs_to_many :campagne_lists
    has_many :campagne_deliveries  

    attr_accessible :name, :subject, :body, :campagne_list_ids

    validates :name, :presence => true, :uniqueness => true
    validates :subject, :presence => true
    validates :body, :presence => true

    def formated_body(token)
      formated_body = body.gsub('||WB||', "<img src=\"#{Rails.application.config.campagne_base_url}/campagne/see/#{token}\" width=\"1\" height=\"1\" />")
      formated_body = formated_body.gsub('||UNSUB||', "#{Rails.application.config.campagne_base_url}/campagne/unsubscribe/#{token}")
      formated_body = formated_body.gsub('||LINK||', "#{Rails.application.config.campagne_base_url}/campagne/click/#{token}?link=")
      # formated_body = formated_body.gsub('||VIEW||', "#{Rails.application.config.campagne_base_url}/campagne/preview/#{token}")
      formated_body
    end

    def preview
      formated_body('0')
    end

  end
end

app/models/campagne/campagne_contact.rb
module Campagne
  class CampagneContact < ActiveRecord::Base
    has_and_belongs_to_many :campagne_lists

    attr_accessible :email, :name

    validates :email, :presence => true, :uniqueness => true
    validates_format_of :email, :with => /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

  end
end

app/models/campagne/campagne_delivery.rb
module Campagne
  class CampagneDelivery < ActiveRecord::Base
    belongs_to :campagne_campaign

    attr_accessible :contact_id, :campagne_list_id , :email, :token

    def see!(request)
      self.ip_address = request.remote_ip if ip_address.blank?
      self.user_agent = request.user_agent if user_agent.blank?
      self.seen_at = Time.now if seen_at.nil?
      save
    end

    def click!(request)
      self.ip_address = request.remote_ip if ip_address.blank?
      self.user_agent = request.user_agent if user_agent.blank?
      self.seen_at = Time.now if seen_at.nil?
      self.clicked_at = Time.now if clicked_at.nil?
      save
    end

    def unsubscribe!(request)
      CampagneList.find(list_id).contacts.delete(CampagneContact.find(contact_id)) # Remove contact from list
      self.ip_address = request.remote_ip if ip_address.blank?
      self.user_agent = request.user_agent if user_agent.blank?
      self.seen_at = Time.now if seen_at.nil?
      self.unsubscribed_at = Time.now if unsubscribed_at.nil?
      save
    end

    def bounce!
      CampagneList.find(list_id).contacts.delete(CampagneContact.find(contact_id))
      update_attribute(:bounced_at, Time.now) if bounced_at.nil?
    end

  end
end

app/models/campagne/campagne_list.rb
module Campagne
  class CampagneList < ActiveRecord::Base
    has_and_belongs_to_many :campagne_contacts
    has_and_belongs_to_many :campagne_campaigns

    attr_accessible :name, :contact_ids

    validates :name, :presence => true, :uniqueness => true

  end
end

app/models/campagne/sender.rb
# encoding: UTF-8
module Campagne
  class Sender

    def self.deliver_email(email, subject, email_body, token)
      sleep 0.5
      ActionMailer::Base::mail({
        :from => "#{Rails.application.config.campagne_from_name} <#{Rails.application.config.campagne_from_email}>",
        :to => email.downcase,
        :subject => subject,
        :body => email_body,
        :content_type => 'text/html; charset=UTF-8',
        :'Return-Path' => "bounce+#{token}@#{Rails.application.config.campagne_domain}",
        :'List-Unsubscribe' => "<mailto:unsubscribe-#{token}@#{Rails.application.config.campagne_domain}>, <#{Rails.application.config.campagne_base_url}/campagne/unsubscribe/#{token}>"
      }).deliver
    end

  end
end

app/models/campagne/sender_job.rb
# encoding: UTF-8
module Campagne
  class SenderJob
    @queue = :default

    def self.generate_token
      token = rand(36**18).to_s(36)
      token = token.gsub('+', '')
      while CampagneDelivery.where(:token => token).first do
        token = rand(36**18).to_s(36)
      end
      token
    end

    def self.perform(campaign_id)
      ActiveSupport::BufferedLogger.new(Rails.root.join('log/resque.log')).info([Time.now.iso8601, $$, "I", "---PERFORM---", campaign_id].join("\t"))
      campaign = Campaign.find(campaign_id)
      contacts = campaign.lists.map(&:contacts).flatten
      contacts = contacts.sort_by {rand} # shuffle
      contacts.each do |contact|
        next if campaign.deliveries.where(:contact_id => contact.id).first
        token = generate_token
        Sender.deliver_email(contact.email, campaign.subject, campaign.formated_body(token), token)
        campaign.deliveries.create(:contact_id => contact.id, :email => contact.email, :token => token)
      end
    end

  end
end

app/controllers/campagne/campagne_campaigns_controller.rb
module Campagne
  class CampagneCampaignsController < ApplicationController
    respond_to :html, :xml
    layout 'campagne/campagne'

    def index
      @campaigns = CampagneCampaign.all
    end

    def show
      @campaign = CampagneCampaign.find(params[:id])
      respond_with(@campaign)
    end

    def new
      @campaign = CampagneCampaign.new
      respond_with(@campaign)
    end

    def create
      @campaign = CampagneCampaign.new(params[:campagne_campagne_campaign])
      flash[:notice] = 'Campaign was successfully created.' if @campaign.save
      respond_with(@campaign, :location => campagne_campagne_campaigns_path)
    end

    def edit
      @campaign = CampagneCampaign.find(params[:id])
      respond_with(@campaign)
    end

    def update
      @campaign = CampagneCampaign.find(params[:id])
      flash[:notice] = 'Campaign was successfully updated.' if @campaign.update_attributes(params[:campagne_campagne_campaign])
      respond_with(@campaign)
    end

    def preview
      @campaign = CampagneCampaign.find(params[:id])
      render :layout => nil
    end

    def deliveries
      @campaign = CampagneCampaign.find(params[:id])
      @deliveries = @campaign.campagne_deliveries
    end

    def schedule
      @campaign = CampagneCampaign.find(params[:id])
      datetime = Time.zone.local(
        params[:schedule][:"at(1i)"].to_i,
        params[:schedule][:"at(2i)"].to_i,
        params[:schedule][:"at(3i)"].to_i,
        params[:schedule][:"at(4i)"].to_i,
        params[:schedule][:"at(5i)"].to_i
      )
      Resque.enqueue_at(datetime, Campagne::SenderJob, @campaign.id)
      redirect_to campagne_campagne_campaign_path(@campaign), :notice => 'Campaign was successfully scheduled.'
    end


  end
end

app/controllers/campagne/campagne_deliveries_controller.rb
module Campagne
  class CampagneDeliveriesController < ApplicationController

    def see
      if delivery = CampagneDelivery.find_by_token(params[:token])
        delivery.see!(request)
      end
      image = File.read(File.join(Rails.root, "public/1x1.gif"))
      send_data image, :type => "image/gif", :disposition => "inline"
    end

    def click
      if delivery = CampagneDelivery.find_by_token(params[:token])
        delivery.click!(request)
      end
      # TODO:
      redirect_to "http://#{params[:link]}"
    end

    def unsubscribe
      if delivery = CampagneDelivery.find_by_token(params[:token])
        delivery.unsubscribe!(request)
        render :text => 'Ok'
      else
        render :text => 'Error'
      end
    end

    def bounce
      if delivery = CampagneDelivery.find_by_token(params[:token])
        delivery.bounce!
        render :text => 'Ok'
      else
        render :text => 'Error'
      end
    end

  end
end

app/controllers/campagne/campagne_lists_controller.rb
module Campagne
  class CampagneListsController < ApplicationController
    respond_to :html, :xml
    layout 'campagne/campagne'

    def index
      @lists = CampagneList.all
    end

    def show
      @list = CampagneList.find(params[:id])
      respond_with(@list)
    end

    def new
      @list = CampagneList.new
      respond_with(@list)
    end

    def create
      @list = CampagneList.new(params[:campagne_campagne_list])
      flash[:notice] = 'List was successfully created.' if @list.save
      respond_with(@list, :location => campagne_campagne_lists_path)
    end

    def import
      @list = CampagneList.find(params[:id])
      if request.post?
        emails = params[:emails].split("\r\n")
        emails.each do |email|
          if contact = CampagneContact.find_by_email(email)
            if !@list.contacts.exists?(contact.id)
              @list.contacts << contact
              @list.save
            end
          else
            @list.contacts.create(:email => email)
          end
        end      
        redirect_to campagne_campagne_lists_path, :notice => "Contacts were successfully imported."
      end
    end

  end
end

app/helpers/campagne/error_messages_helper.rb
module Campagne
  module ErrorMessagesHelper
    # Render error messages for the given objects. The :message and :header_message options are allowed.
    def error_messages_for(*objects)
      options = objects.extract_options!
      options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
      options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
      messages = objects.compact.map { |o| o.errors.full_messages }.flatten
      unless messages.empty?
        content_tag(:div, :class => "error_messages") do
          list_items = messages.map { |msg| content_tag(:li, msg) }
          content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
        end
      end
    end

    module FormBuilderAdditions
      def error_messages(options = {})
        @template.error_messages_for(@object, options)
      end
    end

  end
end

ActionView::Helpers::FormBuilder.send(:include, Campagne::ErrorMessagesHelper::FormBuilderAdditions)

app/views/campagne/campagne_campaigns/_form.html.erb
<%= form_for @campaign do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <strong>You can use these:</strong><br /><br />

    <strong>||WB||</strong> - <a href="http://www.webopedia.com/TERM/W/Web_beacon.html" target="_blank">Web Beacon</a><br /><br />

    <strong>||UNSUB||</strong> - Unsubscribe link<br />
    Ex.: &lt;a href="||UNSUB||"&gt;Click here to unsubscribe&lt;/a&gt;<br /><br />
    
    <strong>||LINK||</strong> - Link<br />
    Ex.: &lt;a href="||LINK||http://www.mysite.com/products/1"&gt;Click to buy&lt;/a&gt;
  </p>
  <p>    
    <%= hidden_field_tag "campagne_campagne_campaign[campagne_list_ids][]", nil%>
    <% Campagne::CampagneList.all.each do |list| %>
      <%= check_box_tag "campagne_campagne_campaign[campagne_list_ids][]", list.id, @campaign.campagne_list_ids.include?(list.id), id: dom_id(list) %>
      <%= label_tag dom_id(list), list.name %><br/>
    <% end %>
  </p>
  <p><%= f.submit 'Create Campaign' %></p>
<% end %>

app/views/campagne/campagne_campaigns/deliveries.html.erb
<h2><%= @campaign.name %></h2>

<table style="width:100%">
  <tr>
    <th>Email</th>
    <th>Token</th>
    <th>Sent at</th>
    <th>Seen at</th>
    <th>Clicked at</th>
    <th>Unsubscribed at</th>
    <th>Bounced at</th>
    <th>IP Address</th>
    <th>User Agent</th>
  </tr>
  <% for delivery in @deliveries %>
    <tr>
      <td><%= delivery.email %></td>
      <td><%= delivery.token %></td>
      <td><%= delivery.created_at %></td>
      <td><%= delivery.seen_at %></td>
      <td><%= delivery.clicked_at %></td>
      <td><%= delivery.unsubscribed_at %></td>
      <td><%= delivery.bounced_at %></td>
      <td><%= delivery.ip_address %></td>
      <td><%= delivery.user_agent %></td>
    </tr>
  <% end %>
</table>

app/views/campagne/campagne_campaigns/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", @campaign %> |
  <%= link_to "View All", campagne_campagne_campaigns_path %>
</p>

app/views/campagne/campagne_campaigns/index.html.erb
<p><%= link_to "New Campaign", new_campagne_campagne_campaign_path %></p>

<table>
  <tr>
    <th>Name</th>
    <th>Subject</th>
  </tr>
  <% for campaign in @campaigns %>
    <tr>
      <td><%= campaign.name %></td>
      <td><%= campaign.subject %></td>
      <td><%= link_to "Preview", preview_campagne_campagne_campaign_path(campaign) %></td>
      <td><%= link_to "Deliveries", deliveries_campagne_campagne_campaign_path(campaign) %></td>
      <td><%= link_to "Show", campaign %></td>
      <td><%= link_to "Edit", edit_campagne_campagne_campaign_path(campaign) %></td>
    </tr>
  <% end %>
</table>

app/views/campagne/campagne_campaigns/new.html.erb
<%= render 'form' %>

<p><%= link_to "Back", campagne_campagne_campaigns_path %></p>

app/views/campagne/campagne_campaigns/preview.html.erb
<%= raw(@campaign.preview) %>

app/views/campagne/campagne_campaigns/show.html.erb
<%= form_tag schedule_campagne_campagne_campaign_path(@campaign) do %>
  <%= datetime_select("schedule", 'at', :default => Time.now) %>
  <%= submit_tag 'Schedule' %>
<% end %>

<p>
  <%= link_to "Preview", preview_campagne_campagne_campaign_path(@campaign) %> |
  <%= link_to "Deliveries", deliveries_campagne_campagne_campaign_path(@campaign) %> | 
  <%= link_to "Edit", edit_campagne_campagne_campaign_path(@campaign) %> |
  <%= link_to "View All", campagne_campagne_campaigns_path %>
</p>

<p>
  <strong>Name:</strong>
  <%= @campaign.name %>
</p>
<p>
  <strong>Subject:</strong>
  <%= @campaign.subject %>
</p>
<p>
  <strong>Lists:</strong><br/>
  <% @campaign.campagne_lists.each do |list| %>
    <%= list.name %><br/>
  <% end %>
</p>
<p>
  <strong>Body:</strong><br />
  <pre>
<%= raw(@campaign.body) %>
  </pre>
</p>